Repository GoogleCloudPlatform/k8s-cluster-bundle, pull requests merged in 2018-11, with the labels that each got.

#93 Fix incorrect json tag on version field
  pkg/apis/bundle/v1alpha1/component_types.go
Labels: size/XS

#92 Fix some typos in the readme
  README.md
  pkg/testutil/fake_reader_writer.go
Labels: lgtm, size/XS

#103 Fix various bugs, lint warnings, go-vet warnings, docs issues.
  pkg/apis/bundle/v1alpha1/component_types.go
  pkg/apis/bundle/v1alpha1/helpers.go
  pkg/apis/bundle/v1alpha1/helpers_test.go
  pkg/core/core.go
  pkg/files/url_scheme.go
  pkg/filter/filter.go
  pkg/inline/inline.go
  pkg/inline/path_rewriter.go
  pkg/maker/maker.go
  pkg/maker/rawyamltmpl/raw_text_maker.go
  pkg/validation/validate_component.go
  pkg/validation/validate_name.go
  pkg/validation/validate_name_test.go
Labels: lgtm, size/M

#100 Add URL validation #97
  pkg/validation/BUILD.bazel
  pkg/validation/validate_component.go
  pkg/validation/validate_url.go
  pkg/validation/validate_url_test.go
Labels: lgtm, ok-to-test, size/L

#108 Rename Filterer to Filter
  pkg/commands/filter/filter.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/maker/common.go
  pkg/maker/rawyamltmpl/raw_text_maker.go
Labels: lgtm, size/S
