Repository GoogleCloudPlatform/k8s-cluster-bundle, pull requests merged in 2019-05, with the labels that each got.

#268 Basic benchmarks
  pkg/build/BUILD.bazel
  pkg/build/inline_benchmark_test.go
  pkg/build/patchbuild_benchmark_test.go
  pkg/options/gotmpl/BUILD.bazel
  pkg/options/gotmpl/go_template_applier_benchmark_test.go
  pkg/options/patchtmpl/BUILD.bazel
  pkg/options/patchtmpl/patch_benchmark_test.go
Labels: size/L

#270 Update go rules, gazelle, and go tool chain in attempt to fix the build.
  WORKSPACE
Labels: lgtm, size/S

#269 Fix minor spelling mistake in Readme
  README.md
Labels: lgtm, needs-ok-to-test, size/XS

#267 Add a dependency solver
  Gopkg.lock
  config/crds/bundle_v1alpha1_bundle.yaml
  config/crds/bundle_v1alpha1_component.yaml
  config/crds/bundle_v1alpha1_componentbuilder.yaml
  config/crds/bundle_v1alpha1_requirements.yaml
  pkg/apis/bundle/v1alpha1/builder_types.go
  pkg/apis/bundle/v1alpha1/component_types.go
  pkg/apis/bundle/v1alpha1/requirement_types.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
  pkg/build/inline.go
  pkg/deps/BUILD.bazel
  pkg/deps/annotation_matcher.go
  pkg/deps/annotation_matcher_test.go
  pkg/deps/collate.go
  pkg/deps/collate_test.go
  pkg/deps/latest.go
  pkg/deps/matcher.go
  pkg/deps/meta.go
  pkg/deps/meta_test.go
  pkg/deps/resolve.go
  pkg/deps/resolve_test.go
  pkg/files/file_reader_writer.go
  pkg/validate/validate_component.go
  pkg/validate/validate_component_test.go
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/BUILD.bazel
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
Labels: size/XXL

#271 Fix bazel file to include jsonnet
  examples/BUILD.bazel
  examples/jsonnet/BUILD.bazel
  pkg/options/jsonnet/BUILD.bazel
Labels: size/XS

#272 Fix golint, gobug, typos
  pkg/apis/bundle/v1alpha1/object_template_types.go
  pkg/apis/bundle/v1alpha1/requirement_types.go
  pkg/deps/annotation_matcher.go
  pkg/options/jsonnet/jsonnet_applier.go
  pkg/options/patchtmpl/patch.go
Labels: lgtm, size/S

#273 Use standard semver library instead of the weird thing I wrote.
  pkg/validate/BUILD.bazel
  pkg/validate/validate_component.go
  pkg/validate/validate_component_test.go
Labels: size/M

#277 Two cleanups for dependency resolution:
  pkg/deps/annotation_matcher.go
  pkg/deps/annotation_matcher_test.go
  pkg/deps/resolve.go
Labels: size/M

#280 Fix an inlining edge case
  pkg/build/inline.go
  pkg/build/inline_test.go
Labels: size/XS

#281 Fix edge case: matching doesn't work for 'fixed' components.
  pkg/deps/resolve.go
  pkg/deps/resolve_test.go
Labels: size/M

#282 Add an error in the case of nil objects.
  pkg/deps/meta.go
Labels: lgtm, size/XS
