Repository GoogleCloudPlatform/k8s-cluster-bundle, pull requests merged in 2019-01, with the labels that each got.

#123 Default to not allowing unknown fields.
  Gopkg.lock
  Gopkg.toml
  pkg/converter/BUILD.bazel
  pkg/converter/muxer.go
  pkg/converter/muxer_test.go
  pkg/find/finder_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/BUILD.bazel
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Labels: size/XXL

#131 Added one more convert iteration from Yaml to Object
  pkg/converter/converter_test.go
Labels: ok-to-test, size/S

#129 Add BundleBuilder and ComponentBuilder Types.
  config/crds/bundle_v1alpha1_bundlebuilder.yaml
  config/crds/bundle_v1alpha1_componentbuilder.yaml
  pkg/apis/bundle/v1alpha1/BUILD.bazel
  pkg/apis/bundle/v1alpha1/builder_types.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/bundle/v1alpha1/zz_generated.register.go
Labels: lgtm, size/L

#130 Add bundlewrapper object for bundle I/O
  pkg/converter/muxer.go
  pkg/testutil/BUILD.bazel
  pkg/testutil/errors.go
  pkg/wrapper/BUILD.bazel
  pkg/wrapper/bundlewrapper.go
  pkg/wrapper/bundlewrapper_test.go
Labels: size/L

#134 Added Bundle and component converters test
  pkg/converter/converter_test.go
Labels: lgtm, ok-to-test, size/M

#135 Finish adding the Builder types
  config/crds/bundle_v1alpha1_bundle.yaml
  config/crds/bundle_v1alpha1_component.yaml
  config/crds/bundle_v1alpha1_componentlist.yaml
  examples/cluster/bundle-builder-example.yaml
  examples/cluster/datablob/data-blob-component.yaml
  examples/cluster/etcd/etcd-component.yaml
  examples/cluster/kubedns/kubedns-component.yaml
  examples/cluster/kubeproxy/kube-proxy-component.yaml
  examples/cluster/kubernetes/kubernetes-component.yaml
  examples/cluster/nodes/nodes-component.yaml
  examples/cluster/options/options-component.yaml
  pkg/apis/bundle/v1alpha1/bundle_types.go
  pkg/apis/bundle/v1alpha1/component_types.go
  pkg/apis/bundle/v1alpha1/helpers.go
  pkg/apis/bundle/v1alpha1/helpers_test.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
  pkg/build/inline_integration_test.go
  pkg/clientset/versioned/BUILD.bazel
  pkg/clientset/versioned/fake/BUILD.bazel
  pkg/clientset/versioned/scheme/BUILD.bazel
  pkg/clientset/versioned/typed/bundle/v1alpha1/BUILD.bazel
  pkg/clientset/versioned/typed/bundle/v1alpha1/fake/BUILD.bazel
  pkg/commands/BUILD.bazel
  pkg/commands/build/BUILD.bazel
  pkg/commands/build/add_commands.go
  pkg/commands/build/build.go
  pkg/commands/cmdlib/BUILD.bazel
  pkg/commands/cmdlib/bundleio.go
  pkg/commands/cmdlib/bundleio_test.go
  pkg/commands/cmdlib/global_options.go
  pkg/commands/filter/filter.go
  pkg/commands/modify/BUILD.bazel
  pkg/commands/modify/images.go
  pkg/commands/root.go
  pkg/converter/converter_integration_test.go
  pkg/converter/example_test.go
  pkg/inline/BUILD.bazel
  pkg/inline/config_map_maker.go
  pkg/inline/config_map_maker_test.go
  pkg/inline/inline.go
  pkg/inline/inline_integration_test.go
  pkg/inline/inline_test.go
  pkg/inline/path_rewriter.go
  pkg/transformer/images.go
  pkg/validate/validate_component.go
Labels: lgtm, size/XXL

#137 Add better examples and docs for patch
  README.md
  cluster_bundle.png
  examples/component/README.md
  examples/component/etcd-component-builder.yaml
  examples/component/etcd-component.yaml
  examples/component/etcd-server.yaml
  pkg/build/inline_integration_test.go
  pkg/converter/converter_integration_test.go
Labels: lgtm, size/L

#138 Add a command for patching.
  examples/component/etcd-component.yaml
  examples/component/etcd-server.yaml
  examples/component/options.yaml
  pkg/commands/BUILD.bazel
  pkg/commands/patch/BUILD.bazel
  pkg/commands/patch/add_commands.go
  pkg/commands/patch/patch.go
  pkg/commands/root.go
  pkg/converter/muxer.go
  pkg/options/common.go
  pkg/options/patchtmpl/patch.go
Labels: lgtm, size/L

#139 Improve docs, examples about patching.
  examples/component/README.md
  examples/component/etcd-component.yaml
  examples/component/etcd-server.yaml
Labels: lgtm, size/M

#144 Improve docs, examples about patching.
  examples/component/README.md
  examples/component/etcd-component.yaml
  examples/component/etcd-server.yaml
Labels: size/XS
