Repository GoogleCloudPlatform/k8s-cluster-bundle, pull requests merged in 2019-02, with the labels that each got.

#147 Move patch template from bundleext/v1alpha1 to bundle/v1alpha1
  config/crds/bundle_v1alpha1_patchtemplate.yaml
  pkg/apis/bundle/v1alpha1/BUILD.bazel
  pkg/apis/bundle/v1alpha1/patch_template_types.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/bundle/v1alpha1/zz_generated.register.go
  pkg/apis/bundleext/v1alpha1/BUILD.bazel
  pkg/commands/modify/images.go
  pkg/commands/patch/patch.go
  pkg/filter/filter.go
  pkg/options/options.go
  pkg/options/patchtmpl/BUILD.bazel
  pkg/options/patchtmpl/patch.go
Labels: lgtm, size/M

#151 Added ToYAMLString() and ToJSONString() methods to converter
  pkg/converter/converter_test.go
  pkg/converter/demuxer.go
Labels: lgtm, ok-to-test, size/M

#150 Generate the component name if it is not specified
  pkg/build/BUILD.bazel
  pkg/build/inline.go
  pkg/build/inline_test.go
Labels: lgtm, size/M

#152 Add openapi validation method.
  pkg/options/openapi/BUILD.bazel
  pkg/options/openapi/conversion.go
  pkg/options/openapi/validate.go
  pkg/options/openapi/validate_test.go
  pkg/options/validate/validate.go
Labels: lgtm, size/L

#154 Docs, examples cleanup for patches.
  examples/component/README.md
  examples/component/etcd-component-builder.yaml
  examples/component/etcd-server.yaml
  examples/component/patches.yaml
Labels: lgtm, size/M

#158 Rename muxer/demuxer to decoder/encoder.
  pkg/converter/BUILD.bazel
  pkg/converter/decoder.go
  pkg/converter/decoder_test.go
  pkg/converter/encoder.go
Labels: lgtm, size/M

#157 Remove image modification command and library.
  pkg/commands/BUILD.bazel
  pkg/commands/modify/BUILD.bazel
  pkg/commands/modify/add_commands.go
  pkg/commands/modify/images.go
  pkg/commands/root.go
  pkg/transformer/BUILD.bazel
  pkg/transformer/doc.go
  pkg/transformer/images.go
  pkg/transformer/images_test.go
Labels: lgtm, size/L

#162 Add support for PatchTemplateBuilder
  examples/patchbuilder/README.md
  examples/patchbuilder/build-options.yaml
  examples/patchbuilder/builder.yaml
  examples/patchbuilder/kube-scheduler.yaml
  examples/patchbuilder/patch-template-builder.yaml
  pkg/build/BUILD.bazel
  pkg/build/patchbuild.go
  pkg/build/patchbuild_test.go
  pkg/commands/build/BUILD.bazel
  pkg/commands/build/add_commands.go
  pkg/commands/build/build.go
  pkg/commands/cmdlib/BUILD.bazel
  pkg/commands/cmdlib/bundleio.go
  pkg/commands/patch/BUILD.bazel
  pkg/commands/patch/patch.go
  pkg/filter/filter.go
  pkg/options/patchtmpl/BUILD.bazel
  pkg/options/patchtmpl/patch.go
  pkg/options/patchtmpl/patch_test.go
Labels: lgtm, size/XL

#164 Implement stripping applied patches from the component
  pkg/commands/patch/add_commands.go
  pkg/commands/patch/patch.go
  pkg/options/common.go
  pkg/options/patchtmpl/patch.go
  pkg/options/patchtmpl/patch_test.go
  pkg/options/simpletemplate/simple_applier.go
Labels: lgtm, size/L

#165 Implement the export command.
  examples/patchbuilder/README.md
  examples/patchbuilder/build-options.yaml
  examples/patchbuilder/builder.yaml
  examples/patchbuilder/deploy-options-1.yaml
  examples/patchbuilder/deploy-options-2.yaml
  examples/patchbuilder/deployment-patch-builder.yaml
  examples/patchbuilder/helloweb-deployment.yaml
  examples/patchbuilder/helloweb-service-clusterip.yaml
  examples/patchbuilder/kube-scheduler.yaml
  examples/patchbuilder/patch-template-builder.yaml
  examples/patchbuilder/service-patch.yaml
  pkg/commands/BUILD.bazel
  pkg/commands/cmdlib/cmdlib.go
  pkg/commands/export/BUILD.bazel
  pkg/commands/export/add_commands.go
  pkg/commands/export/export.go
  pkg/commands/root.go
Labels: lgtm, size/L

#168 Add support for nested properties during patch template building.
  pkg/build/BUILD.bazel
  pkg/build/patchbuild.go
  pkg/build/patchbuild_test.go
Labels: size/L

#169 Rework the top-level Readme, following the v0.9.0 release
  README.md
Labels: lgtm, size/L

#170 Rename ComponentsFromName to ComponentVersions
  pkg/find/finder.go
Labels: lgtm, size/XS

#171 Encoder/decoder cleanups.
  pkg/build/inline.go
  pkg/build/inline_integration_test.go
  pkg/build/inline_test.go
  pkg/converter/converter_integration_test.go
  pkg/converter/converter_test.go
  pkg/converter/decoder.go
  pkg/converter/encoder.go
  pkg/converter/example_test.go
  pkg/converter/exporter_test.go
  pkg/filter/filter_test.go
  pkg/find/finder_test.go
  pkg/find/images_test.go
  pkg/options/rawyamltmpl/raw_text_applier_test.go
  pkg/options/simpletemplate/simple_applier_test.go
  pkg/validate/validate_component_test.go
Labels: size/L

#172 Implement export of Bundle to ComponentSet
  config/crds/bundle_v1alpha1_bundlebuilder.yaml
  pkg/apis/bundle/v1alpha1/BUILD.bazel
  pkg/apis/bundle/v1alpha1/builder_types.go
  pkg/apis/bundle/v1alpha1/helpers.go
  pkg/apis/bundle/v1alpha1/helpers_test.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
  pkg/build/inline.go
  pkg/build/inline_test.go
  pkg/commands/export/BUILD.bazel
  pkg/commands/export/export.go
  pkg/wrapper/BUILD.bazel
  pkg/wrapper/bundlewrapper.go
Labels: lgtm, size/L

#177 Move file/std io to top-level to allow for dependency-injection.
  pkg/commands/BUILD.bazel
  pkg/commands/build/add_commands.go
  pkg/commands/build/build.go
  pkg/commands/cmdlib/cmdlib.go
  pkg/commands/export/add_commands.go
  pkg/commands/export/export.go
  pkg/commands/filter/add_commands.go
  pkg/commands/filter/filter.go
  pkg/commands/find/add_commands.go
  pkg/commands/find/images.go
  pkg/commands/patch/add_commands.go
  pkg/commands/patch/patch.go
  pkg/commands/root.go
  pkg/commands/validate/add_commands.go
  pkg/commands/validate/validate.go
Labels: lgtm, size/L

#176 Change string-map flag to more standard format.
  examples/component/README.md
  pkg/commands/build/add_commands.go
  pkg/commands/build/build.go
  pkg/commands/cmdlib/bundleio.go
  pkg/commands/filter/add_commands.go
  pkg/commands/filter/filter.go
  pkg/commands/patch/add_commands.go
  pkg/commands/patch/patch.go
Labels: lgtm, size/M

#179 Chdir to the appropriate directory when run with bazel.
  pkg/build/BUILD.bazel
  pkg/build/bazel_init_test.go
  pkg/build/inline_integration_test.go
  pkg/converter/bazel_init_test.go
  pkg/converter/converter_integration_test.go
  pkg/testutil/testutil.go
Labels: lgtm, size/M

#180 Add componentsuite, which adds functionality for testing components.
  README.md
  examples/BUILD.bazel
  examples/cluster/BUILD.bazel
  examples/component/BUILD.bazel
  examples/patchbuilder/BUILD.bazel
  examples/patchbuilder/bazel_init_test.go
  examples/patchbuilder/component-test.yaml
  examples/patchbuilder/component_test.go
  pkg/build/BUILD.bazel
  pkg/build/patchbuild.go
  pkg/converter/BUILD.bazel
  pkg/testutil/componentsuite/BUILD.bazel
  pkg/testutil/componentsuite/bazel_init_test.go
  pkg/testutil/componentsuite/componentsuite.go
  pkg/testutil/componentsuite/componentsuite_test.go
  pkg/testutil/componentsuite/schema.go
Labels: size/XL

#181 Add a test-suite for the component example
  examples/BUILD.bazel
  examples/component/BUILD.bazel
  examples/component/bazel_init_test.go
  examples/component/component_test.go
  examples/component/etcd-component-test.yaml
  examples/component/patches.yaml
Labels: size/L

#185 Improve documentation related to patching and component testing.
  README.md
  examples/component/bazel_init_test.go
  examples/component/component_test.go
  examples/component/test-suite.yaml
  examples/patchbuilder/component_test.go
  examples/patchbuilder/test-suite.yaml
  pkg/testutil/componentsuite/componentsuite.go
  pkg/testutil/componentsuite/componentsuite_test.go
  pkg/testutil/componentsuite/schema.go
Labels: lgtm, size/L

#187 Allow caller to define template missing key policy in patch templates
  pkg/options/options.go
  pkg/options/patchtmpl/patch.go
Labels: lgtm, size/S

#190 Fix up some tests to make some imports/tooling happier.
  examples/component/bazel_init_test.go
  examples/component/component_test.go
  examples/patchbuilder/bazel_init_test.go
  examples/patchbuilder/component_test.go
Labels: lgtm

#193 Less logging
  pkg/build/patchbuild.go
  pkg/commands/cmdlib/bundleio.go
  pkg/commands/patch/patch.go
Labels: lgtm, size/XS

#186 Add a Requirements object to specify package-time deps.
  config/crds/bundle_v1alpha1_bundle.yaml
  config/crds/bundle_v1alpha1_component.yaml
  config/crds/bundle_v1alpha1_componentbuilder.yaml
  config/crds/bundle_v1alpha1_componentlist.yaml
  config/crds/bundle_v1alpha1_requirements.yaml
  pkg/apis/bundle/v1alpha1/BUILD.bazel
  pkg/apis/bundle/v1alpha1/builder_types.go
  pkg/apis/bundle/v1alpha1/component_types.go
  pkg/apis/bundle/v1alpha1/requirement_types.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/bundle/v1alpha1/zz_generated.register.go
Labels: lgtm, size/L

#196 Clean up go lint and go vet warnings.
  pkg/apis/bundle/v1alpha1/helpers_test.go
  pkg/build/inline.go
  pkg/build/patchbuild.go
  pkg/build/patchbuild_test.go
  pkg/commands/build/build.go
  pkg/commands/cmdlib/bundleio.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/find/images_test.go
  pkg/options/options.go
  pkg/options/rawyamltmpl/raw_text_applier_test.go
  pkg/options/simpletemplate/simple_applier_test.go
  pkg/testutil/componentsuite/componentsuite.go
  pkg/testutil/componentsuite/schema.go
Labels: lgtm, size/L

#191 Bundlectl version command
  cmd/bundlectl/main.go
  pkg/commands/BUILD.bazel
  pkg/commands/root.go
  pkg/commands/version/BUILD.bazel
  pkg/commands/version/add_commands.go
  pkg/version/BUILD.bazel
  pkg/version/version.go
Labels: lgtm, size/M

#198 Improve config map builders.
  config/crds/bundle_v1alpha1_bundlebuilder.yaml
  config/crds/bundle_v1alpha1_componentbuilder.yaml
  config/crds/bundleext_v1alpha1_nodeconfig.yaml
  pkg/apis/bundle/v1alpha1/builder_types.go
  pkg/apis/bundle/v1alpha1/component_types.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
  pkg/build/config_map_maker.go
  pkg/build/inline.go
  pkg/build/inline_test.go
Labels: lgtm, size/L

#205 Add component set reference type
  pkg/apis/bundle/v1alpha1/component_types.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
  pkg/build/BUILD.bazel
Labels: lgtm, size/M

#206 Update bundlectl version and add the appropriate copyright headers.
  pkg/commands/version/add_commands.go
  pkg/version/version.go
Labels: size/M

#207 Use klog
  Gopkg.lock
  Gopkg.toml
  pkg/clientset/versioned/BUILD.bazel
  pkg/clientset/versioned/clientset.go
  pkg/commands/build/BUILD.bazel
  pkg/commands/build/build.go
  pkg/commands/cmdlib/BUILD.bazel
  pkg/commands/cmdlib/bundleio.go
  pkg/commands/cmdlib/cmdlib.go
  pkg/commands/export/BUILD.bazel
  pkg/commands/export/export.go
  pkg/commands/filter/BUILD.bazel
  pkg/commands/filter/filter.go
  pkg/commands/find/BUILD.bazel
  pkg/commands/find/images.go
  pkg/commands/patch/BUILD.bazel
  pkg/commands/patch/patch.go
  pkg/commands/validate/BUILD.bazel
  pkg/commands/validate/validate.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/BUILD.bazel
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: ok-to-test, size/XXL

#174 Add validation url
  pkg/build/inline_integration_test.go
  pkg/commands/validate/BUILD.bazel
  pkg/commands/validate/validate.go
  pkg/validate/BUILD.bazel
  pkg/validate/validate_component.go
  pkg/validate/validate_component_test.go
Labels: lgtm, size/XL

#208 Use klog (#207)
  Gopkg.lock
  Gopkg.toml
  pkg/clientset/versioned/BUILD.bazel
  pkg/clientset/versioned/clientset.go
  pkg/commands/build/BUILD.bazel
  pkg/commands/build/build.go
  pkg/commands/cmdlib/BUILD.bazel
  pkg/commands/cmdlib/bundleio.go
  pkg/commands/cmdlib/cmdlib.go
  pkg/commands/export/BUILD.bazel
  pkg/commands/export/export.go
  pkg/commands/filter/BUILD.bazel
  pkg/commands/filter/filter.go
  pkg/commands/find/BUILD.bazel
  pkg/commands/find/images.go
  pkg/commands/patch/BUILD.bazel
  pkg/commands/patch/patch.go
  pkg/commands/validate/BUILD.bazel
  pkg/commands/validate/validate.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/BUILD.bazel
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: lgtm, size/XXL

#209 Make inline not able to be set.
  pkg/commands/build/build.go
  pkg/commands/root.go
Labels: size/XS
