Repository GoogleCloudPlatform/k8s-cluster-bundle, pull requests merged in 2019-04, with the labels that each got.

#260 Added check if there is no patch templates
  pkg/options/patchtmpl/patch.go
Labels: lgtm, ok-to-test, size/S

#263 Add a patch template type.
  config/crds/bundle_v1alpha1_patchtemplate.yaml
  config/crds/bundle_v1alpha1_patchtemplatebuilder.yaml
  hack/boilerplate.go.txt
  pkg/apis/bundle/v1alpha1/patch_template_types.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/bundle/v1alpha1/zz_generated.register.go
  pkg/clientset/versioned/clientset.go
  pkg/clientset/versioned/doc.go
  pkg/clientset/versioned/fake/clientset_generated.go
  pkg/clientset/versioned/fake/doc.go
  pkg/clientset/versioned/fake/register.go
  pkg/clientset/versioned/scheme/doc.go
  pkg/clientset/versioned/scheme/register.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/bundle_client.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/component.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/componentset.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/doc.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/fake/doc.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/fake/fake_bundle_client.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/fake/fake_component.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/fake/fake_componentset.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/generated_expansion.go
Labels: lgtm, size/M

#264 Use patch type to apply JSON patches
  Gopkg.lock
  pkg/apis/bundle/v1alpha1/patch_template_types.go
  pkg/options/patchtmpl/BUILD.bazel
  pkg/options/patchtmpl/patch.go
  pkg/options/patchtmpl/patch_test.go
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/BUILD.bazel
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/google/go-jsonnet/release.sh
  vendor/github.com/google/go-jsonnet/reset_stdast_go.sh
  vendor/github.com/google/go-jsonnet/testdata/object_comp_illegal.golden
  vendor/github.com/google/go-jsonnet/testdata/object_comp_illegal.jsonnet
  vendor/github.com/google/go-jsonnet/tests.sh
  vendor/github.com/google/go-jsonnet/travisBuild.sh
Labels: lgtm, size/XXL

#265 Bump the bundlectl version
  pkg/version/version.go
Labels: lgtm, size/XS

#266 Update release-0.11 branch with cherry picks
  Gopkg.lock
  config/crds/bundle_v1alpha1_patchtemplate.yaml
  config/crds/bundle_v1alpha1_patchtemplatebuilder.yaml
  hack/boilerplate.go.txt
  pkg/apis/bundle/v1alpha1/patch_template_types.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/bundle/v1alpha1/zz_generated.register.go
  pkg/clientset/versioned/clientset.go
  pkg/clientset/versioned/doc.go
  pkg/clientset/versioned/fake/clientset_generated.go
  pkg/clientset/versioned/fake/doc.go
  pkg/clientset/versioned/fake/register.go
  pkg/clientset/versioned/scheme/doc.go
  pkg/clientset/versioned/scheme/register.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/bundle_client.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/component.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/componentset.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/doc.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/fake/doc.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/fake/fake_bundle_client.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/fake/fake_component.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/fake/fake_componentset.go
  pkg/clientset/versioned/typed/bundle/v1alpha1/generated_expansion.go
  pkg/options/patchtmpl/BUILD.bazel
  pkg/options/patchtmpl/patch.go
  pkg/options/patchtmpl/patch_test.go
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/BUILD.bazel
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/google/go-jsonnet/release.sh
  vendor/github.com/google/go-jsonnet/reset_stdast_go.sh
  vendor/github.com/google/go-jsonnet/testdata/object_comp_illegal.golden
  vendor/github.com/google/go-jsonnet/testdata/object_comp_illegal.jsonnet
  vendor/github.com/google/go-jsonnet/tests.sh
  vendor/github.com/google/go-jsonnet/travisBuild.sh
Labels: lgtm, size/XXL
