Repository GoogleCloudPlatform/k8s-cluster-bundle, pull requests merged in 2019-03, with the labels that each got.

#212 get rid of context action
  pkg/commands/build/add_commands.go
  pkg/commands/cmdlib/BUILD.bazel
  pkg/commands/cmdlib/cmdlib.go
  pkg/commands/export/add_commands.go
  pkg/commands/filter/add_commands.go
  pkg/commands/find/add_commands.go
  pkg/commands/patch/add_commands.go
  pkg/commands/validate/add_commands.go
Labels: lgtm, size/M

#213 Add an ObjectTemplateBuilder type.
  pkg/apis/bundle/v1alpha1/object_template_types.go
  pkg/build/inline.go
  pkg/build/inline_test.go
Labels: size/L

#216 Fix lint errors.
  pkg/commands/version/add_commands.go
  pkg/validate/validate_component.go
Labels: lgtm, size/XS

#217 Harden/clarify the patching logic.
  Gopkg.lock
  examples/patchbuilder/deployment-patch-builder.yaml
  examples/patchbuilder/helloweb-deployment.yaml
  pkg/build/BUILD.bazel
  pkg/commands/cmdlib/BUILD.bazel
  pkg/options/patchtmpl/BUILD.bazel
  pkg/options/patchtmpl/patch.go
  pkg/options/patchtmpl/patch_test.go
  pkg/options/patchtmpl/scheme.go
  pkg/validate/BUILD.bazel
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/BUILD.bazel
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
Labels: lgtm, size/XXL

#218 Add more types to scheme for release 0.10 and don't fall back to json-patch
  Gopkg.lock
  examples/patchbuilder/deployment-patch-builder.yaml
  examples/patchbuilder/helloweb-deployment.yaml
  pkg/options/patchtmpl/BUILD.bazel
  pkg/options/patchtmpl/patch.go
  pkg/options/patchtmpl/patch_test.go
  pkg/options/patchtmpl/scheme.go
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/BUILD.bazel
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
Labels: lgtm, size/XXL

#229 Update finder with an AllComponents method
  pkg/find/finder.go
Labels: lgtm, size/XS

#230 Make a copy of the component before doing transformations.
  pkg/options/gotmpl/go_template_applier.go
  pkg/options/gotmpl/go_template_applier_test.go
  pkg/options/patchtmpl/patch.go
Labels: lgtm, size/M

#232 Fix some lint errors
  pkg/apis/bundle/v1alpha1/object_template_types.go
  pkg/commands/build/get_command.go
  pkg/commands/export/get_command.go
  pkg/commands/filter/get_command.go
  pkg/commands/find/get_command.go
  pkg/commands/patch/get_command.go
  pkg/commands/validate/get_command.go
  pkg/commands/version/get_command.go
  pkg/find/finder.go
  pkg/validate/validate_component_test.go
Labels: lgtm, size/M

#231 Init command
  pkg/commands/BUILD.bazel
  pkg/commands/build/BUILD.bazel
  pkg/commands/export/BUILD.bazel
  pkg/commands/filter/BUILD.bazel
  pkg/commands/generate/BUILD.bazel
  pkg/commands/generate/get_command.go
  pkg/commands/root.go
  pkg/generate/BUILD.bazel
  pkg/generate/generate.go
Labels: lgtm, size/L

#241 Remove the old appliers.
  pkg/options/rawyamltmpl/BUILD.bazel
  pkg/options/rawyamltmpl/raw_text_applier.go
  pkg/options/rawyamltmpl/raw_text_applier_test.go
  pkg/options/simpletemplate/BUILD.bazel
  pkg/options/simpletemplate/simple_applier.go
  pkg/options/simpletemplate/simple_applier_test.go
Labels: lgtm, size/XL

#237 Some cleanups for the generate command.
  pkg/commands/generate/BUILD.bazel
  pkg/commands/generate/get_command.go
  pkg/commands/root.go
  pkg/generate/BUILD.bazel
  pkg/generate/generate.go
  pkg/options/patchtmpl/BUILD.bazel
  pkg/options/patchtmpl/scheme.go
Labels: lgtm, size/M

#243 simple example test using version
  cmd/bundlectl/integration_tests/BUILD
  cmd/bundlectl/integration_tests/version.sh
Labels: lgtm, size/S

#245 Change finder.ComponentVersions to return references
  pkg/find/finder.go
Labels: lgtm, size/S

#244 Remove excludes from requirements (at least for now).
  config/crds/bundle_v1alpha1_objecttemplate.yaml
  config/crds/bundle_v1alpha1_requirements.yaml
  pkg/apis/bundle/v1alpha1/requirement_types.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/M

#251 Fix list meta.
  hack/update-codegen.sh
  pkg/apis/bundle/v1alpha1/component_types.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/S

#252 Fix ListMeta and add more types to the scheme
  pkg/apis/bundle/v1alpha1/component_types.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
  pkg/clientset/versioned/BUILD.bazel
  pkg/clientset/versioned/clientset.go
  pkg/options/patchtmpl/BUILD.bazel
  pkg/options/patchtmpl/scheme.go
Labels: size/S

#246 Add selector to patch template types
  pkg/apis/bundle/v1alpha1/patch_template_types.go
Labels: lgtm, size/M

#255 Add apps/v1beta2 to patcher scheme
  cmd/bundlectl/integration_tests/BUILD
  pkg/options/patchtmpl/BUILD.bazel
  pkg/options/patchtmpl/scheme.go
Labels: lgtm, size/S

#256 Update selector codegen
  config/crds/bundle_v1alpha1_patchtemplate.yaml
  config/crds/bundle_v1alpha1_patchtemplatebuilder.yaml
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/L

#257 Add support for the ObjectSelector.
  README.md
  config/crds/bundle_v1alpha1_patchtemplate.yaml
  config/crds/bundle_v1alpha1_patchtemplatebuilder.yaml
  pkg/apis/bundle/v1alpha1/patch_template_types.go
  pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go
  pkg/commands/filter/filter.go
  pkg/commands/filter/get_command.go
  pkg/filter/BUILD.bazel
  pkg/filter/doc.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/options/patchtmpl/patch.go
  pkg/options/patchtmpl/patch_test.go
Labels: lgtm, size/XL

#258 Add a multi-applier applier
  pkg/options/gotmpl/go_template_applier.go
  pkg/options/multi/BUILD.bazel
  pkg/options/multi/multi.go
  pkg/options/multi/multi_test.go
Labels: lgtm, size/L
