Repository GoogleCloudPlatform/k8s-cluster-bundle, pull requests merged in 2020-08, with the labels that each got.

#303 Add webhook v1beta1 to default patcher
  pkg/options/patchtmpl/BUILD.bazel
  pkg/options/patchtmpl/scheme.go
Labels: lgtm, ok-to-test, size/XS

#304 Update Release 0.12
  pkg/options/patchtmpl/BUILD.bazel
  pkg/options/patchtmpl/scheme.go
  pkg/version/version.go
Labels: size/XS

#308 Add TemplateFiles to ComponentBuilder
  examples/templatefiles/BUILD.bazel
  examples/templatefiles/README.md
  examples/templatefiles/bazel_init_test.go
  examples/templatefiles/builder.yaml
  examples/templatefiles/component_test.go
  examples/templatefiles/etcd-template.yaml
  examples/templatefiles/test-suite.yaml
  pkg/apis/bundle/v1alpha1/builder_types.go
  pkg/build/inline.go
  pkg/build/inline_test.go
Labels: lgtm, size/L
