Repository GoogleCloudPlatform/k8s-cluster-bundle, pull requests merged in 2022-05, with the labels that each got.

#318 Modify examples/patchbuilder/deployment-patch-builder.yaml to reproduce number comparison issue.
  examples/patchbuilder/deployment-patch-builder.yaml
Labels: size/XS, needs-ok-to-test

#319 Add test cases for patch template builder edgcase
  examples/patchbuilder/deployment-patch-builder.yaml
  pkg/build/patchbuild.go
  pkg/converter/converter_test.go
  pkg/options/openapi/validate.go
  pkg/options/patchtmpl/patch_test.go
Labels: size/M, lgtm

#323 Add a float convert helper for patch templates.
  pkg/options/patchtmpl/patch.go
  pkg/options/patchtmpl/patch_test.go
Labels: size/L
